services:
  - name: backend
    type: web
    env: docker
    plan: free
    repo: https://github.com/Prashant-900/KrackHack-YARA-ALL-THE-WAY
    dockerContext: ./backend
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000

  - name: teamBeluga
    type: web
    env: docker
    plan: free
    repo: https://github.com/Prashant-900/KrackHack-YARA-ALL-THE-WAY
    dockerContext: ./frontend

  - name: nginx
    type: web
    env: docker
    plan: free
    repo: https://github.com/Prashant-900/KrackHack-YARA-ALL-THE-WAY
    dockerContext: ./nginx
