# Use Node.js image to build frontend
FROM node:18 AS build

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy project files and build
COPY . .
RUN npm run build

# Use Nginx for serving frontend
FROM nginx:latest
COPY --from=build /app/dist /usr/share/nginx/html

# Copy frontend Nginx configuration
COPY nginx-frontend.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
